/**:
  ros__parameters:
    # v4l2_camera specific settings
    image_size: [1280, 720]
    time_per_frame: [1, 60]
    pixel_format: "MJPG"
    
    output_encoding: "rgb8" 
    
    image_raw:
      compressed:
        format: "jpeg"
        jpeg_quality: 95